#!/usr/bin/env bash

_minecraft() {
    local cur="${COMP_WORDS[COMP_CWORD]}" \
          prev="${COMP_WORDS[COMP_CWORD - 1]}" \
          reply=() space=1 i

    if [[ $cur == -* ]]; then
        reply=(--gamedir --jar --world --memory --debug --help)
    elif [[ $prev == @(-g|--gamedir) ]]; then
        space=0
        reply=($(compgen -d -- "$cur"))
        for ((i = 0; i < ${#reply[@]}; ++i)); do
            reply[i]+='/'
        done
    elif [[ $prev == @(-j|--jar) ]]; then
        space=0
        local tmp=($(compgen -f -- "$cur"))
        for ((i = 0; i < ${#tmp[@]}; ++i)); do
            local path="${tmp[i]}"
            if [[ -d "$path" ]]; then
                reply+=("$path/")
            elif [[ $path == *.jar ]]; then
                reply+=("$path ")
            fi
        done
    elif [[ $prev == @(-w|--world) ]]; then
        local IFS=$'\n'
        reply=($(ruby -r shellwords -e '
            puts Dir["/srv/games/minecraft/saves/*/*"].map { |d| File.basename d }
        '))
    elif [[ $prev == @(-m|--memory) ]]; then
        for ((i = 1; i <= 16; ++i)); do
            reply+=($((256 * i)))
        done
    else
        reply=(start stop restart update repl)
    fi

    ((space)) && compopt +o nospace

    local IFS=$'\n'
    COMPREPLY=($(compgen -W "${reply[*]}" -- "$cur"))
}

complete -F _minecraft -o nospace minecraft
